Dan 361
vwt-digital-solutions/fttx-dashboard pull request #47
Opened 2020-10-08 12:17 UTC by cvanhouten

Moeilijk pull request, merge met develop ging niet goed.

2020-10-09 11:18 UTC, avanturnhout requested changes

2020-10-09 11:18 UTC, avanturnhout commented on dashboard/analyse_dashboard/analyse/fttx.code-workspace
> +		"python.pythonPath": "/Users/caspervanhouten/anaconda3/envs/ftx-analyse-3/bin/python"
Kan het niet zo goed inschatten maar willen deze url niet in de config hebben?

2020-10-09 11:18 UTC, avanturnhout commented on dashboard/analyse_dashboard/analyse/functions.py
> +def get_project_dates(date_FTU0, date_FTU1, y_target_l, x_prog, x_d, rc1, d_real_l):
Prima zo, qua logica is dit nog steeds omslachtig, ik moet hier nog een keer goed naar kijken. Misschien pak ik het mee met de FTU callback.

2020-10-09 11:18 UTC, avanturnhout commented on dashboard/firebase-debug.log
> +[debug] [2020-09-24T14:20:57.262Z] ----------------------------------------------------------------------
Is dit iets wat mee moet in de commits of meer iets voor de .gitignore?

2020-10-09 11:18 UTC, avanturnhout commented on dashboard/firestore-debug.log
> +API endpoint: http://localhost:8080
Zelfde hier, .gitignore?

2020-10-09 11:18 UTC, avanturnhout commented on dashboard/layout/pages/kpn.py
> +                id="tmobile-overview",
Waarom zit hier een tmobile referentie op de kpn pagina?

2020-10-09 11:18 UTC, avanturnhout commented on dashboard/layout/pages/tmobile/overview.py
> +    # jaaroverzicht = collection.get_document(collection="Data", graph_name="jaaroverzicht", client=client)
Waarom is dit uitgecomment?

2020-10-09 11:18 UTC, avanturnhout commented on dashboard/layout/pages/tmobile/overview.py
> +    # jaaroverzicht = collection.get_document(collection="Data", graph_name="jaaroverzicht", client=client)
Betekent dit dat we geen werkende pagina hebben na mergen??

2020-10-12 12:55 UTC, closed without merging

2020-10-12 12:55 UTC, ErikVWT commented
Merged locally and pushed to dev